### ISSUE TITLE
How to update a data?please

### ISSUE THREAD

**Issue by CodeK1988** [ahmedrizwan/RxRecyclerAdapter#10]
thanks.

**Comment by ahmedrizwan** [comment]
Create an instance of RxDataSource and call method updateDataSet on it. That should do the trick. 

`rxDataSource.updateDataSet(dataSet).updateAdapter(); `

More details and examples can be found [here](https://medium.freecodecamp.com/simplifying-recyclerview-adapters-with-rx-databinding-f02ebed0b386#.szj7kdqz1).

**Comment by CodeK1988** [comment]
Thanks.
