### ISSUE TITLE
ItemLayoutBinding

### ISSUE THREAD

**Issue by CodeK1988** [ahmedrizwan/RxRecyclerAdapter#4]
can you tell me... ItemLayoutBinding? thanks!

**Comment by ahmedrizwan** [comment]
ItemLayoutBinding represents the **generated Binding** from the xml layout file. 
For example if you have _header_layout.xml_

``` xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="@dimen/activity_horizontal_margin">

        <TextView android:id="@+id/textViewItem"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  tools:text="Recycler Item"/>

    </LinearLayout>
</layout>
```

 Then in code you'll be creating RxDataSource like this

``` java
RxDataSource<String> rxDataSource = new RxDataSource<>(dataSet);
//compose, bind and subscribe!
rxDataSource.<HeaderLayoutBinding>bindRecyclerView(recyclerView, R.layout.header_layout) 
      .subscribe(viewHolder -> {
        ...
      });
```

Make sure you have DataBinding **enabled** in your _build.gradle_ file. 
And also if you're project isn't resolving _HeaderLayoutBinding_, then click on **Make Project** under Build menu, then it should be resolved. 

For more detailed information and examples, refer to this [article](https://medium.com/@ahmedrizwan/simplifying-recyclerview-adapters-with-rx-databinding-f02ebed0b386#.s4dpopdag).

**Comment by CodeK1988** [comment]
thank you very much! 
I forgot to add 
dataBinding {//数据绑定
        enabled = true
    }

**Comment by Polyterative** [comment]
Also make sure to have you layout starting with 

```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
>
```
otherwise binding won't show up at all
___

Still mine doesn't compile
