### ISSUE TITLE
 How to set Adapter onItemClick  event it please?

### ISSUE THREAD

**Issue by CodeK1988** [ahmedrizwan/RxRecyclerAdapter#5]
I follow you.And thanks a lot. You open my eyes. but how to set Adapter onItemClick event it ?please 。 like this?
 rxDataSource.repeat(1).
                <ItemHomepageGridviewBinding>bindRecyclerView(fragmentBinding.mGridView, R.layout.item_homepage_gridview)
                .subscribe(viewHolder -> {
                    RelativeLayout.LayoutParams param = new RelativeLayout.LayoutParams(ViewGroup
                            .LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
                    ItemHomepageGridviewBinding dataBinding = viewHolder.getViewDataBinding();
                    param.width=screenWidth/3;
                    param.height = screenWidth/5;
                    dataBinding.gridviewRoot.setLayoutParams(param);
                    long itemId = viewHolder.getItemId();
                    String item = viewHolder.getItem();
                    if(itemId < lastCount){
                        Picasso.with(getActivity()).load(item).into(dataBinding.gridviewNetImage);
                    }else{
                        dataBinding.gridviewNetImage.setImageResource(R.drawable.gridview_background);
                    }
                    dataBinding.getRoot().setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {

```
                    }
                });
            });
```

**Comment by ahmedrizwan** [comment]
Yes @yizuochengchi that's the right way to set onClickListener... You can also use Databinding's Binding Adapters... Which I think would be a better approach... 
I'll share an example of that here, in a little while...
