### ISSUE TITLE
Can I use this adapter without databinding?

### ISSUE THREAD

**Issue by lenguyenthanh** [ahmedrizwan/RxRecyclerAdapter#6]

**Comment by ahmedrizwan** [comment]
Hi @lenguyenthanh... I'm afraid you can't use it without DataBinding. 
The adapter needed to be generic. And for that, DataBinding does become an integral part of the library.

**Comment by mohsin** [comment]
@ahmedrizwan I think you could shift this library out of databinding to use kotlin's newer [Android Extensions's "View binding" instead](https://kotlinlang.org/docs/tutorials/android-plugin.html#layoutcontainer-support). Right now LayoutContainer is experimental but once it's stable I think this library could shift to that and make it free of the older databinding way.

**Comment by ahmedrizwan** [comment]
Thank you @SaifurRahmanMohsin for the suggestion. LayoutContainer looks promising. 
I'll give it a try - and will move away from Databinding as soon as it's stable (or maybe even before)

Side note: I don't prefer using Databinding anymore and my current preference is actually using [Epoxy](https://github.com/airbnb/epoxy) in large-scale projects. So I'd recommend you check that out as well.
